### ISSUE TITLE
improve structure of gradle dependencies and version definitions

### ISSUE THREAD

**Issue by twatzl** [boudicca-events/boudicca.events#172]
Currently we have a lot of duplicate definitions in the gradle files, which are redefined for every module.

- [ ] use gradle version catalogs https://medium.com/@callmeryan/gradle-version-catalog-728111fa210f and migrate all dependencies
- [x] somehow apply the gradle plugins (kotlin/jvm, spring, springboot) globally for all subprojects with -server or -api suffix
- [x] set the java version globally for all jvm projects

**Comment by kadhonn** [comment]
i will close this issue since we have the issue #256 for the gradle version catalog and the other two points are already done
