### ISSUE TITLE
fix run configurations + add run configuration for empty eventdb

### ISSUE THREAD

**Issue by twatzl** [boudicca-events/boudicca.events#239]
the packages in the run configurations are not correct anymore and need to be fixed.

also currently eventdb is filled with example data. however for some usecases another run configuration would be required to start eventdb empty.

**Comment by kadhonn** [comment]
which launch configurations are you talking about? i just double checked all checked-in launch configs and they do work.

also, the eventdb locally uses a file called boudicca.store in the root project directory to store its data. so if you want an empty eventdb just stop it, delete this file and restart it

**Comment by kadhonn** [comment]
is there any update from your side about this? otherwise i would close this issue
