### ISSUE TITLE
Implement suggestions for better first time user experience

### ISSUE THREAD

**Issue by Yolgie** [boudicca-events/boudicca.events#299]
Part of the result of the User Tests #289 should be concrete improvements for first time users.

Coordinate with your other USCC Fellows to discuss possible features and create tickets for them.

**Comment by mahdikhashan** [comment]
the first suggestion was to add some sort of extra information in the header to clearly mention the purpose of the website, 

**"all accessible events in Austria"**

![Image](https://github.com/boudicca-events/boudicca.events/assets/58775404/95c4ac82-e4fc-43dc-a4b1-5d39037ef8d5)
