### ISSUE TITLE
ui-bug: event does not have a replacement image

### ISSUE THREAD

**Issue by mahdikhashan** [boudicca-events/boudicca.events#354]
![image](https://github.com/boudicca-events/boudicca.events/assets/58775404/91024ee2-92c5-4bf7-916d-b2f38c8ca21d)
![image](https://github.com/boudicca-events/boudicca.events/assets/58775404/d94c02b8-1e2e-4d70-93a0-12b665ce9a2d)

**Comment by kadhonn** [comment]
ohh yeah, that has to be the Sport category i added
we need a replacement icon for that
i totally forgot about it
