### ISSUE TITLE
package publishing: publish all packages with the same version number

### ISSUE THREAD

**Issue by twatzl** [boudicca-events/boudicca.events#573]
currently https://central.sonatype.com/artifact/events.boudicca/semantic-conventions is version 0.4.1 while https://central.sonatype.com/artifact/events.boudicca/search-client is 0.5.0.

This makes is confusing what versions are working together properly.

Proposed solution:

Only publish all packages as one release.

**Comment by kadhonn** [comment]
this is because it is now called "common-model" and not "semantic-conventions" anymore
