### ISSUE TITLE
Upgrade to OpenAPI 3.1.0 and make the api generate from code again

### ISSUE THREAD

**Issue by Yolgie** [boudicca-events/boudicca.events#96]

**Comment by kadhonn** [comment]
didn't we talk about getting rid of the openapi generator? or maybe we will just write our own templates?
but i am in favor of getting rid of it, i really dislike it

**Comment by Yolgie** [comment]
ok, maybe the description is not clear enough, the target should be that there is a single source of truth for the api's again

**Comment by kadhonn** [comment]
as far as i know @twatzl is still working on it?

**Comment by kadhonn** [comment]
this also was finally done and is working again
